version: '3'

services:
  eureka:
    build: eureka
    ports: 
      - "8761:8761"
    expose:
      - "8761"

  travel_agent:
    build: travel_agent
    depends_on:
      - eureka
      - flights
      - hotels
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    links:
      - eureka
    ports:
      - "8081:8081"
    expose:
      - "8081"

  flights:
    build: flights
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
    links:
      - eureka
    ports:
      - "8082:8082"
    expose:
      - "8082"

  hotels:
    build: hotels
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - eureka
    links:
      - eureka
    ports:
      - "8089:8089"
    expose:
      - "8089"



  