apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: flights
  name: flights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        app: flights
    spec:
      containers:
      - env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://10.103.202.113:8761/eureka/
        image: conchobar/flights:latest
        imagePullPolicy: ""
        name: flights
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
