apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: hotels
  name: hotels
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hotels
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: hotels
    spec:
      containers:
      - env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:8761/eureka/
        image: hotels
        imagePullPolicy: ""
        name: hotels
        ports:
        - containerPort: 8089
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
