apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-http
spec:
  type: NodePort
  ports:
    - port: 8100  
      targetPort: 876
      nodePort: 31000
  selector: 
    component: travel-agent