apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: travel-agent
  name: travel-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: travel-agent
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: travel-agent
    spec:
      containers:
      - env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://10.103.202.113:8761/eureka/
        image: conchobar/travel_agent:latest
        imagePullPolicy: ""
        name: travel-agent
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
