apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: travel
  name: travel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: travel
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        app: travel
    spec:
      containers:
      - env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: _JAVA_OPTIONS
          value: -Deureka.client.serviceUrl.defaultZone=http://eureka-0.eureka:8761/eureka/,http://eureka-1.eureka:8761/eureka/ -Deureka.instance.preferIpAddress=true
                  -Deureka.client.registryFetchIntervalSeconds=15
        - name: EUREKA_CLIENT_REGISTERWITHEUREKA
          value: "true"
        - name: EUREKA_CLIENT_FETCHREGISTRY
          value: "true"
        # - name: MONGODB_ATLAS
        #   value: mongodb+srv://tanmayjoshi:tanmaypass@cluster-quaranteam.sr96d.mongodb.net/bookings?retryWrites=true&w=majority
        # - name: FRONT_SERVER_PORT
        #   value: "8080"
        # - name: spring_profiles_active
        #   value: dev

        # The hostnames must match with the the eureka serviceUrls, otherwise the replicas are reported as unavailable in the eureka dashboard      
        # - name: EUREKA_INSTANCE_HOSTNAME
        #   value: ${MY_POD_NAME}.eureka
        image: conchobar/travel_agent:latest
        imagePullPolicy: ""
        name: travel
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
